apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  labels: {app: guestbook, tier: frontend}
spec:
  selector: {app: guestbook, tier: frontend}
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
